In [1]:
# ---------------------------------------------------------- 
#    Chap 01: Tuples in Julia
#    Author: Dr. Saad Laouadi
# 
#.   Copyright to Dr Saad Laouadi
#   Using the examples from the notebook directly into 
#.  lecture is not allowed.
# -----------------------------------------------------------

## Tuples in Julia 

In [2]:
function print_banner(char::Char, num_chars::Int, message::String)
    border = repeat(string(char), num_chars)
    
    total_padding = num_chars - length(message)
    left_padding = total_padding ÷ 2
    right_padding = total_padding - left_padding
    
    centered_message = repeat(" ", 
        left_padding) * message * repeat(" ", right_padding)
    
    println(border)
    println(centered_message)
    println(border)
end;

In [3]:
# Different ways to create tuples
tuple1 = (1, 2, 3, 4, 5)                  # Creating a tuple with specific elements
tuple2 = ()                               # Creating an empty tuple
tuple3 = (1, "apple", 3.14, true)         # Creating a tuple with mixed types
tuple4 = (1,)                             # Creating a single-element tuple
tuple5 = (1:3, 4:6)                       # Creating a tuple with ranges
tuple6 = (a=1, b="banana", c=2.71);       # Creating a named tuple

In [4]:
print_banner('+', 60, "Tuples in Julia")

# Displaying tuples
println("tuple1: ", tuple1)
println("tuple2: ", tuple2)
println("tuple3: ", tuple3)
println("tuple4: ", tuple4)
println("tuple5: ", tuple5)
println("tuple6: ", tuple6)

# Basic operations with tuples
println("\nBasic Operations with Tuples:")

# Accessing elements
println("  First element of tuple1: ", tuple1[1])
println("  Last element of tuple1 : ", tuple1[end])

# Accessing elements in mixed type tuple
println("  Second element of tuple3: ", tuple3[2])

# Length of the tuple
println("  Length of tuple1: ", length(tuple1))

# Iterating over elements in a tuple
println("  Iterating over tuple1: ")
for elem in tuple1
    println("    ", elem)
end

# Unpacking tuple elements
a, b, c, d, e = tuple1
println("  Unpacked elements of tuple1: ", a, ", ", b, ", ", c, ", ", d, ", ", e)

# Accessing elements in a named tuple
println("  Accessing named tuple element by name: ", tuple6.a)
println("  Accessing named tuple element by index: ", tuple6[2])

print_banner('+', 62, "Tuple Comprehensions are Generators")
# Tuple comprehensions

tuple_comprehension1 = (i for i in 1:5)                     # Simple comprehension
tuple_comprehension2 = (i^2 for i in 1:5)                   # Squares of numbers from 1 to 5
tuple_comprehension3 = (i * j for i in 1:3, j in 1:3)       # Multiplication table
tuple_comprehension4 = (i for i in 1:10 if i % 2 == 0)      # Even numbers from 1 to 10

# Displaying tuples created using comprehensions
println("tuple_comprehension1:\n", tuple_comprehension1)
println("tuple_comprehension2:\n", tuple_comprehension2)
println("tuple_comprehension3:\n", tuple_comprehension3)
println("tuple_comprehension4:\n", tuple_comprehension4)

println(repeat('+', 60))

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                      Tuples in Julia                       
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
tuple1: (1, 2, 3, 4, 5)
tuple2: ()
tuple3: (1, "apple", 3.14, true)
tuple4: (1,)
tuple5: (1:3, 4:6)
tuple6: (a = 1, b = "banana", c = 2.71)

Basic Operations with Tuples:
  First element of tuple1: 1
  Last element of tuple1 : 5
  Second element of tuple3: apple
  Length of tuple1: 5
  Iterating over tuple1: 
    1
    2
    3
    4
    5
  Unpacked elements of tuple1: 1, 2, 3, 4, 5
  Accessing named tuple element by name: 1
  Accessing named tuple element by index: banana
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             Tuple Comprehensions are Generators              
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
tuple_comprehension1:
Base.Generator{UnitRange{Int64}, typeof(identity)}(identity, 1:5)
tuple_comprehension2:
Base.Generator{UnitRange{Int64}, var"#1#

In [5]:
print_banner('+', 62, "Creating Tuples using comprehensions with Collect");

# Collecting tuple comprehensions
collected_tuple_comprehension1 = collect((i for i in 1:5))                     # Simple comprehension
collected_tuple_comprehension2 = collect((i^2 for i in 1:5))                   # Squares of numbers from 1 to 5
collected_tuple_comprehension3 = collect((i * j for i in 1:3, j in 1:3))       # Multiplication table
collected_tuple_comprehension4 = collect((i for i in 1:10 if i % 2 == 0))      # Even numbers from 1 to 10

# Displaying collected tuples created using comprehensions
println("collected_tuple_comprehension1: ", collected_tuple_comprehension1)
println("collected_tuple_comprehension2: ", collected_tuple_comprehension2)
println("collected_tuple_comprehension3: ", collected_tuple_comprehension3)
println("collected_tuple_comprehension4: ", collected_tuple_comprehension4)

println(repeat('+', 62))

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      Creating Tuples using comprehensions with Collect       
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
collected_tuple_comprehension1: [1, 2, 3, 4, 5]
collected_tuple_comprehension2: [1, 4, 9, 16, 25]
collected_tuple_comprehension3: [1 2 3; 2 4 6; 3 6 9]
collected_tuple_comprehension4: [2, 4, 6, 8, 10]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


In [6]:
?collect

search: collect collected_tuple_comprehension4 collected_tuple_comprehension3



```
collect(element_type, collection)
```

Return an `Array` with the given element type of all items in a collection or iterable. The result has the same shape and number of dimensions as `collection`.

# Examples

```jldoctest
julia> collect(Float64, 1:2:5)
3-element Vector{Float64}:
 1.0
 3.0
 5.0
```

---

```
collect(collection)
```

Return an `Array` of all items in a collection or iterator. For dictionaries, returns `Vector{Pair{KeyType, ValType}}`. If the argument is array-like or is an iterator with the [`HasShape`](@ref IteratorSize) trait, the result will have the same shape and number of dimensions as the argument.

Used by comprehensions to turn a generator into an `Array`.

# Examples

```jldoctest
julia> collect(1:2:13)
7-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13

julia> [x^2 for x in 1:8 if isodd(x)]
4-element Vector{Int64}:
  1
  9
 25
 49
```
